System.MissingMethodException: 没有为该对象定义无参数的构造函数。MVC runtime doesn't know how to create a controller that doesn't have a default constructor. A default constructor is a constructor that doesn't have any parameters. It's parameterless. That fortunately is a very easy problem to fix. That fortunately is a very easy problem to fix. What  need to do is plug in some additional components into the MVC runtime that can create that controller, and there are several of these components out there. They are typically known as inversion of control containers. There's one called Ninject. Microsoft has one called Unity. I'm going to go out and look for one called StructureMap and I'm going to look for the MVC3 version of StructureMap ************************************************************************************************************* Dependency Injection